<script>
    import { goto } from '$app/navigation';
    
    import { parse } from 'csv-parse';
    import { Readable } from 'node:stream';
  
    function navigateToManageCategories() {
        goto('/manageCategories');
    }

    function navigateToManageGoals() {
        goto('/manageGoals');
    }

    function navigateBack() {
        history.go(-1);
    }

	function parseCSVFile() {
        var delimeter  = ','; // what seperates csv data
        var newline ='\n';
        var element = document.getElementById('file');
        var table = document.getElementById('table');

        // ? as a maybe - if its not null we execute
        // change event executed with input elements
        //element?.addEventListener('change', function () {
           // if (!!element?.files && element?.files.length > 0)
        //})
    }
</script>

<head>
    <title>Transactions</title>
</head>

<div class="button-row">
    <button onclick={navigateToManageCategories} class="button">Manage Categories</button>
    <button onclick={navigateToManageGoals} class="button">Manage Goals</button>

    <!-- add <option> stuff here after u do file import -->

    <label for="file">Upload</label>
    <input id="file" multiple type="file" class="hidden" />

    <label for="upload">Month</label>
    <select class="select">Month</select>

    <label for="upload">Year</label>
    <select class="select">Year</select>


    <button onclick={navigateBack} class="button">Back</button>
</div>

<div class="table">
    <!-- will be generated by JavaScript -->
     <table id="table">

     </table>
</div>

<style>
    .button, select, label{
        width: auto;
        box-shadow: var(--shadow-sm);
        border-radius: var(--radius-lg);
        background-color: var(--color-blue-500);
        color: white;
        padding: 7px;
    }

    .button:hover {
        background-color: rgb(53, 53, 255);
    }

    .table {
        border-collapse: collapse;
        width: auto;
        height: auto;
        border-bottom: 1px solid #ddd;
    }

    .th, td {
        padding: 10px;
        
    }

    /* zebra striped table */
    tr:nth-child(even) {background-color: #f2f2f2;}
</style>