<div class="button-row">
    <button class="button">Manage Categories</button>
    <button class="button">Manage Goals</button>
    <select class="select">Upload</select>
    <select class="select">Month</select>
    <select class="select">Year</select>
    <button class="button">Back</button>
</div>

<div class="table">
    <!-- will be generated by JavaScript -->
</div>

<style>
    .button, select{
        width: auto;
        box-shadow: var(--shadow-sm);
        border-radius: var(--radius-lg);
        background-color: rgb(78, 78, 255);
        color: white;
        padding: 7px;
        margin: 5px;
    }

    .button:hover {
        background-color: rgb(53, 53, 255);
    }

    .table {
        border-collapse: collapse;
        width: auto;
        height: auto;
        border-bottom: 1px solid #ddd;
    }

    .th, td {
        padding: 10px;
        
    }

    /* zebra striped table */
    tr:nth-child(even) {background-color: #f2f2f2;}
</style>