<head>
    <title>Manage Categories</title>
</head>

<div class="button">
    <button class="w-20 shadow-sm rounded bg-blue-500 hover:bg-blue-600 text-white py-1">Back</button>
</div>

<style>
    .button {
        display: flex;
        justify-content: flex-end;
        margin: 3px;
    }
</style>

<script>
    let todo = '';
</script>

<form class="my-6">
    <label class="font-bold text-gray-800 m-3" for="todo">Add Category</label>
    <div class="flex flex-row text-sm mb-2">
        <!-- bind todo value inside input (to store the variable there)-->
        <input type="text" bind:value={todo} name="todo" placeholder="Food"
        class="appearance-none shadow-sm border border-gray-200 p-2 focus:outline-non focus:border-gray-500
        rounded-lg"/>
        <button type="submit" class="w-auto shadow-sm rounded bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 m-2">Add</button>
    </div>

</form>

<div class="table">
    <!-- will be generated by JavaScript -->
</div>
