<head>
    <title>Manage Goals</title>
</head>

<div class="button">
    <button class="w-20 shadow-sm rounded bg-blue-500 hover:bg-blue-600 text-white py-1">Back</button>
</div>

<style>
    .button {
        display: flex;
        justify-content: flex-end;
        margin: 3px;
    }
    .table {

    }
</style>

<table>
 <!-- will be generated by JavaScript -->
</table>